//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_DOCS_FILES
    {
        public int FIRM_CODE { get; set; }
        public int PRMY_TRNS_CLSS { get; set; }
        public long DOC_NBR { get; set; }
        public decimal SEQ { get; set; }
        public byte[] BIN_FILE_DATA { get; set; }
        public string MIME_TYPE { get; set; }
        public string FILE_EXTENSION { get; set; }
    }
}
