//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_HH_LGSTC_FRCST
    {
        public string PART_CODE { get; set; }
        public decimal QNTY { get; set; }
        public decimal LINE_NBR { get; set; }
        public decimal DOC_NBR { get; set; }
        public string PART_NAME { get; set; }
        public string RMRK { get; set; }
        public decimal ID { get; set; }
    }
}
