//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_HH_USERS
    {
        public string USER_NAME { get; set; }
        public decimal IS_ADMIN { get; set; }
        public string STRM_CODE { get; set; }
        public string SMSUSER { get; set; }
        public string STC_NBR { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public string MOVE_TO_STRM { get; set; }
        public string PASSWORDH { get; set; }
        public string EMAIL_USER { get; set; }
    }
}
