//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUMM_HH_DSTN_WEB
    {
        public string DSTN_KEY { get; set; }
        public string DIRA { get; set; }
        public int DSTN_CODE { get; set; }
        public string DSTN_NAME { get; set; }
        public string CELL { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> ISPREF { get; set; }
        public string SALE_SUB_AREA { get; set; }
    }
}
