//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUMM_HH_HNDL_CALLS
    {
        public long DOC_NBR { get; set; }
        public int LINE_NBR { get; set; }
        public Nullable<System.DateTime> LINE_EVNT_DATE { get; set; }
        public Nullable<System.DateTime> RQSTD_SHIP_DATE { get; set; }
        public Nullable<System.DateTime> LINE_EXPR_DATE { get; set; }
        public string PARENT_STRM_CODE { get; set; }
        public string STRM_CODE { get; set; }
        public string STRM_NAME { get; set; }
        public string CALL_DSCR { get; set; }
        public string APT_CODE { get; set; }
        public string APT_NAME { get; set; }
        public string APT_SHRT_NAME { get; set; }
        public Nullable<int> DSTN_CODE { get; set; }
        public string DSTN_NAME { get; set; }
        public string CELL_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> CALL_STAT_CODE { get; set; }
        public string CALL_STAT { get; set; }
        public string CALL_STAT_DATE { get; set; }
        public string CALL_STAT_RMRK { get; set; }
        public string CALL_STAT_FULL { get; set; }
        public string BILL_TO_CUST_CODE { get; set; }
        public Nullable<System.DateTime> OPEN_DATE { get; set; }
        public Nullable<decimal> HAS_IMAGES { get; set; }
        public string CALL_RMRK { get; set; }
    }
}
