//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUMM_HH_IMAGES_LINKS
    {
        public int FIRM_CODE { get; set; }
        public int PRMY_TRNS_CLSS { get; set; }
        public Nullable<decimal> DOC_NBR { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<decimal> SEQ { get; set; }
    }
}
