//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUMM_HH_WORK_PARTS
    {
        public string WORK_PART_ID { get; set; }
        public string PART_CODE { get; set; }
        public string PART_LONG_NAME { get; set; }
        public string PART_SHRT_NAME { get; set; }
        public Nullable<int> UNIT_CODE { get; set; }
        public string UNIT_NAME { get; set; }
        public string PRMY_STRM_CODE { get; set; }
        public string TMP_PART_NAME_Y_N { get; set; }
        public string PART_GRP_CODE { get; set; }
        public string PART_CODE_NAME { get; set; }
        public string RSRV_STRM_CODE { get; set; }
        public Nullable<int> DFLT_PART { get; set; }
        public Nullable<decimal> TEST { get; set; }
    }
}
