//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeHelpCallsWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUMM_HH_CALLS_LINES
    {
        public decimal LINE_ID { get; set; }
        public Nullable<long> DOC_NBR { get; set; }
        public Nullable<int> LINE_NBR { get; set; }
        public string PART_CODE { get; set; }
        public string PART_NAME { get; set; }
        public string PART_CODE_NAME { get; set; }
        public Nullable<decimal> QNTY { get; set; }
        public Nullable<int> UNIT_CODE { get; set; }
        public string UNIT_NAME { get; set; }
        public string TXT_DSCR { get; set; }
        public string PARENT_STRM_CODE { get; set; }
        public Nullable<decimal> ORD { get; set; }
        public Nullable<decimal> RO { get; set; }
    }
}
